# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UpdateDataUsingElements' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UpdateDataUsingElements
    pod 'AEXML', '4.6.1'
#   pod 'Skyflow', '1.24.2'
    pod 'Skyflow', :git => 'https://github.com/skyflowapi/skyflow-iOS.git', :branch => 'release/26.3.1'

  target 'UpdateDataUsingElementsTests' do
    inherit! :search_paths
    # Pods for testing
     pod 'AEXML', '4.6.1'
#   pod 'Skyflow', '1.24.2'
    pod 'Skyflow', :git => 'https://github.com/skyflowapi/skyflow-iOS.git', :branch => 'release/26.3.1'
  end

  target 'UpdateDataUsingElementsUITests' do
    # Pods for testing
  	pod 'AEXML', '4.6.1'
#   pod 'Skyflow', '1.24.2'
    pod 'Skyflow', :git => 'https://github.com/skyflowapi/skyflow-iOS.git', :branch => 'release/26.3.1'

  end

end
