# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'CollectAndRevealSample' do
  #use_frameworks!
  pod 'AEXML', '4.6.1'

  # Pods for skyflow-iOS-sample-app
  pod 'Skyflow', ">= 1.22.0" 

end
