# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'PullFundsSample' do
  #use_frameworks!

  # Pods for skyflow-iOS-sample-app
  pod 'Skyflow'

end
