platform :ios, '13.0'
target 'Validations' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SkyflowFlowVault', '1.26.0'

  # Pods for Validations

end
