# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'InputFormatting' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    
  pod 'Skyflow', '1.19.0'

  # Pods for InputFormatting

  target 'InputFormattingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InputFormattingUITests' do
    # Pods for testing
  end

end
