# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'


target 'ComposableElements' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ComposableElements
  pod 'Skyflow', ">= 1.19.0" 

  target 'ComposableElementsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ComposableElementsUITests' do
    # Pods for testing
  end

end
