platform :ios, '13.0'
target 'InputFormatting' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SkyflowFlowVault', '1.26.0'

  # Pods for InputFormatting

  target 'InputFormattingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InputFormattingUITests' do
    # Pods for testing
  end

end
