# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'GetSample' do
  #use_frameworks!

  # Pods for GetSample
  pod 'Skyflow', ">= 1.19.0" 

end
