platform :ios, '13.0'
target 'UpdateDataUsingElements' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SkyflowFlowVault', :git => 'https://github.com/skyflowapi/skyflow-iOS.git', :branch => 'release/26.8.2'

  # Pods for UpdateDataUsingElements

  target 'UpdateDataUsingElementsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UpdateDataUsingElementsUITests' do
    # Pods for testing
  end

end
