name: Public Beta Release

on:
  push:
    tags: '*.*.*-beta.*'


jobs:
  deploy_public_beta_pod:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_ACTIONS }}
      
    - name: Get Previous tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@v1
      with:
        fallback: 1.0.0

    - name: Deploy to Cocoapods
      run: |
           set -eo pipefail
           pod lib lint --allow-warnings
           pod trunk push --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
