name: Upload Coverage

on:
  push:
    branches:
      - main

jobs:
  CoverageReport:
    name: Xcode Build
    runs-on: macOS-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Select Xcode 15
        run: sudo xcode-select --switch /Applications/Xcode_15.1.app/Contents/Developer

      - name: Prepare iOS 17 Simulator
        run: sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
             sudo ln -s /Applications/Xcode_15.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 17.0.1.simruntime
             xcrun simctl list runtimes
      
      - name: Build and Test
        run: xcodebuild clean -workspace .swiftpm/xcode/package.xcworkspace -scheme Skyflow -enableCodeCoverage YES -destination "platform=iOS Simulator,OS=17.0.1,name=iPhone 15" VAULT_URL="${{ secrets.VAULT_URL }}" TEST_SKYFLOW_ID1="${{ secrets.TEST_SKYFLOW_ID1 }}" TEST_SKYFLOW_ID2="${{ secrets.TEST_SKYFLOW_ID2 }}" TEST_SKYFLOW_ID3="${{ secrets.TEST_SKYFLOW_ID3 }}" TEST_SKYFLOW_ID4="${{ secrets.TEST_SKYFLOW_ID4 }}" VAULT_ID="${{ secrets.VAULT_ID }}" test
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}


