name: CI Checks

on: [pull_request]

jobs:
  SwiftLint:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v1
     - name: SwiftLint 
       uses: norio-nomura/action-swiftlint@3.2.1
       env:
         DIFF_BASE: ${{ github.base_ref }}
       with:
          args: --config .swiftlint.yml
  xcode-build:
    name: Xcode Build
    runs-on: macOS-10.15
    timeout-minutes: 30

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Select Xcode 12
        run: sudo xcode-select --switch /Applications/Xcode_12.2.app/Contents/Developer
      
      - name: Prepare iOS 13 Simulator
        run: sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
             sudo ln -s /Applications/Xcode_11.7.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 13.6.simruntime
             xcrun simctl list runtimes
      
      - name: Build and Test
        run: xcodebuild clean -workspace .swiftpm/xcode/package.xcworkspace -scheme Skyflow -destination "platform=iOS Simulator,OS=14.2,name=iPhone 11" VAULT_URL="${{ secrets.VAULT_URL }}" CAVV_TEST_TOKEN="${{ secrets.CAVV_TEST_TOKEN }}" PULL_FUNDS_INTEGRATION_CONNECTION_URL="${{ secrets.PULL_FUNDS_INTEGRATION_CONNECTION_URL }}" CVV_INTEGRATION_PATH="${{ secrets.CVV_INTEGRATION_PATH }}" CVV_INTEGRATION_CONNECTION_URL="${{ secrets.CVV_INTEGRATION_CONNECTION_URL }}" CONNECTION_URL="${{ secrets.CONNECTION_URL }}" TEST_EXPIRATION_DATE_TOKEN="${{ secrets.TEST_EXPIRATION_DATE_TOKEN }}" TEST_CARD_NUMBER="${{ secrets.TEST_CARD_NUMBER }}" TEST_SKYFLOW_ID1="${{ secrets.TEST_SKYFLOW_ID1 }}" TEST_SKYFLOW_ID2="${{ secrets.TEST_SKYFLOW_ID2 }}" TEST_SKYFLOW_ID3="${{ secrets.TEST_SKYFLOW_ID3 }}" TEST_SKYFLOW_ID4="${{ secrets.TEST_SKYFLOW_ID4 }}" DETOKENIZE_TEST_TOKEN="${{ secrets.DETOKENIZE_TEST_TOKEN }}" DETOKENIZE_TEST_VALUE="${{ secrets.DETOKENIZE_TEST_VALUE }}" TOKEN_ENDPOINT="${{ secrets.TOKEN_ENDPOINT }}" PULL_FUNDS_INTEGRATION_ID="${{ secrets.PULL_FUNDS_INTEGRATION_ID }}" VISA_BASIC_AUTH="${{ secrets.VISA_BASIC_AUTH }}" CVV_INTEGRATION_ID="${{ secrets.CVV_INTEGRATION_ID }}" VAULT_ID="${{ secrets.VAULT_ID }}" test
        
      - name: Gather code coverage
        run: xcrun llvm-cov export -format="lcov" .build/debug/SkyflowPackageTests.xctest/Contents/MacOS/SkyflowPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./coverage_report.lcov
          verbose: true

