name: CI Checks

on: [pull_request]

jobs:
  xcode-build:
    name: Xcode Build
    runs-on: macOS-10.15
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Select Xcode 12
        run: sudo xcode-select --switch /Applications/Xcode_12.2.app/Contents/Developer
      
      - name: Prepare iOS 13 Simulator
        run: sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
             sudo ln -s /Applications/Xcode_11.7.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 13.6.simruntime
             xcrun simctl list runtimes
      
      - name: Build and Test
        run: set -o pipefail && xcodebuild clean -workspace .swiftpm/xcode/package.xcworkspace -scheme Skyflow -destination "platform=iOS Simulator,OS=14.2,name=iPhone 11" test

